name: Build and Deploy App to Firebase Distribution

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Create file
        run: cat /home/runner/work/FurryFriends/FurryFriends/app/google-services.json | base64

      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/FurryFriends/FurryFriends/app/google-services.json

      - name: Build and Deploy Debug
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}